export const WORD_TYPES = [
  { key: 'noun', label: 'Sustantivos', icon: '📚' },
  { key: 'verb', label: 'Verbos', icon: '🏃' },
  { key: 'adjective', label: 'Adjetivos', icon: '🎨' },
  { key: 'adverb', label: 'Adverbios', icon: '⚡' },
  { key: 'preposition', label: 'Preposiciones', icon: '🔗' },
  { key: 'conjunction', label: 'Conjunciones', icon: '🔗' },
  { key: 'personal pronoun', label: 'Pronombres Personales', icon: '👤' },
  { key: 'possessive pronoun', label: 'Pronombres Posesivos', icon: '👤' },
  { key: 'article', label: 'Artículos', icon: '📝' },
  { key: 'determiner', label: 'Determinantes', icon: '📋' },
  { key: 'quantifier', label: 'Cuantificadores', icon: '🔢' },
  { key: 'interjection', label: 'Interjecciones', icon: '💬' },
  { key: 'auxiliary verb', label: 'Verbos Auxiliares', icon: '🔧' },
  { key: 'modal verb', label: 'Verbos Modales', icon: '🔧' },
  { key: 'infinitive', label: 'Infinitivos', icon: '♾️' },
  { key: 'participle', label: 'Participios', icon: '📝' },
  { key: 'gerund', label: 'Gerundios', icon: '🔄' },
  { key: 'phrasal verb', label: 'Phrasal Verbs', icon: '🔗' },
  { key: 'other', label: 'Otros', icon: '📦' },
]; 